name = "Merpcraftfabric 1"
author = "Bamsy"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5a98c4e00a0488e007717ece8c8880cc94067ea21534f3d1f3f5d71974351de"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
