name = "Merpcraftfabric 1"
author = "Bamsy"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38163cf887a6f5d2cfc3f3583af92cb187b50e86d69d9774447644eca7ad1120"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
