name = "Merpcraftfabric 1"
author = "Bamsy"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "efe45a38fe34f6e1eb4604080a6faaa638cd40a52e4d8324893ddc8192035129"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
