name = "Merpcraftfabric 1"
author = "Bamsy"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18d51c4c285c543c6412cbbaf87555fb5a167e4a574faac6971a9cb8773174b2"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
