name = "Merpcraftfabric 1"
author = "Bamsy"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9505a56b44392796ad2a38bfca8e8f5bc88227fe1c30936f438fe8c01106538e"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
