name = "Merpcraftfabric 1"
author = "Bamsy"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d56f0c92cb8e997b9c45735e24f3213ba1c18b4a2fb6d9a2714f2d7bf5075bf"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
