name = "Merpcraftfabric 1"
author = "Bamsy"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "32ebd1d4374f080c33632bba24c6d553c585d4fe7af69329e914064998c15d58"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
