name = "Merpcraftfabric 1"
author = "Bamsy"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97baa5cfe2b6b42efcd66d864248e67be702cf9ee553da85b78a05546b8f1676"

[versions]
fabric = "0.14.12"
minecraft = "1.19.2"
